import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()
db_url = os.getenv("DATABASE_URL")

conn = psycopg2.connect(db_url)
conn.autocommit = True
cursor = conn.cursor()

tables = ['users', 'groups', 'expenses', 'expense_splits', 'expense_messages', 'expense_approvals', 'pending_invites']

for table in tables:
    cursor.execute(f"SELECT column_default, is_identity FROM information_schema.columns WHERE table_name = '{table}' AND column_name = 'id'")
    print(f"{table}: {cursor.fetchone()}")
    
    # Let's alter the table to add GENERATED BY DEFAULT AS IDENTITY
    # But first we check if it already has it.
    try:
        cursor.execute(f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;")
        print(f"Added IDENTITY to {table}.id")
    except Exception as e:
        print(f"Could not add IDENTITY to {table}: {e}")
        
    try:
        cursor.execute(f"SELECT MAX(id) FROM {table}")
        max_id = cursor.fetchone()[0] or 1
        
        # In Postgres 10+, identities are tied to a sequence behind the scenes but we can use RESTART
        cursor.execute(f"ALTER TABLE {table} ALTER COLUMN id RESTART WITH {max_id + 1};")
        print(f"Restarted sequence for {table} to {max_id + 1}")
    except Exception as e:
        print(f"Could not RESTART sequence for {table}: {e}")

conn.close()
